### ISSUE TITLE
See how much control we have over the Bluetooth parameters

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#1]
For instance: transmit power, etc.

**Comment by josuah** [comment]
Also investigate this related bug:

The Bluetooth NUS disconnects after a few seconds. Regardless of what is being done (transmitting/receiving, or idle), or which client is in use (Android app, python script).

**Comment by siliconwitch** [comment]
https://docs.silabs.com/bluetooth/4.0/miscellaneous/mobile/selecting-suitable-connection-parameters-for-apple-devices
