### ISSUE TITLE
Enable `camera.capture()` function

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/monocle-micropython#131]

**Comment by josuah** [comment]
I need to get my FPGA up again...

**Comment by josuah** [comment]
I might get it to work by powering them externally.

**Comment by josuah** [comment]
This got some progress in the https://github.com/sathibault/streamlogic-monocle-micropython branch, which will now need to be integrated onto the https://github.com/brilliant/monocle-micropython branch
