### ISSUE TITLE
[feature] Discuss whether we want automatic GC

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#135]
Related discussion:
https://discord.com/channels/963222352534048818/1080079396687319080

**Comment by siliconwitch** [comment]
I think this is already automatic 🤔 maybe worth checking this https://docs.micropython.org/en/latest/library/gc.html#gc.threshold

**Comment by josuah** [comment]
News from the chat:

> sending this
> ```
> display.text("${getDateTimeStr()}", 0, 0, 0xffffff)`,
>       'display.show()
> ```
> about 70 times and the monocle reboots

**Comment by siliconwitch** [comment]
Can be set using `gc.threshold()` at startup
