### ISSUE TITLE
[bug] not getting OK printed in raw mode

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#142]
This seems to only happen on the latest firmware from `dev`, rather than in the latest release:

**Comment by siliconwitch** [comment]
Seems fine for me. How are you testing?
```python
MicroPython v1.19.1-837-g67fac4ebc on 2023-03-03; Monocle on nRF52832
Type "help()" for more information.
>>> 
raw REPL; CTRL-B to exit
>OK>OKhi
>OK>
```

**Comment by josuah** [comment]
I was testing with the serial_console.py script.
I will try to reproduce with various methods, and if none does, close that issue.
Thank you for testing!
