### ISSUE TITLE
Inquiry about Product Capabilities: Data Display, Image Showing, and Microphone Ability

### ISSUE THREAD

**Issue by randomwangran** [brilliantlabsAR/monocle-micropython#149]
I watched the YouTube video of the product that drew a 2D red line using MicroPython Web REPL. I am interested in knowing the current status of the product's capabilities. My first question is whether the product can retrieve data from the SD card memory and display it on the screen. I am also curious about how the product can manipulate the display of text. My second question pertains to whether the product can display pictures or PNG data. Can the product manipulate png on the screen? Lastly, I am curious about the product's microphone ability. Can the product capture voice memos? Thank you for your attention to my inquiry. I am thinking about buying your product.

Thanks,

**Comment by josuah** [comment]
Thank you for your curiosity toward that project, and sorry for the long delay for the answer.

> whether the product can retrieve data from the SD card memory and display it on the screen
There is no SD card connector or integration, but there is an embedded flash chip, that will be made available to store files on it. File transfer would go through the same MicroPython Bluetooth console.

> I am also curious about how the product can manipulate the display of text.
There is a drawing library that can take charge of that:
https://docs.brilliantmonocle.com/micropython/micropython/#display--monocle-specific
`text("hello world", 10, 30, 0xFF7700)` entered into the Monocle Bluetooth console would display an orange "hello world" string on top left corner of the screen.

> My second question pertains to whether the product can display pictures or PNG data.
It could be a bit too slow to decode JPEG or PNG directly, but the FPGA chip onboard can be good at this kind of data processing. https://streamlogic.io/docs/reify/ is a tool that facilitates these kind of use-cases. Storing the image in raw format (i.e. converting it before storing it to the Monocle) would likely already work, by simply passing along the data from the file to the display.

> Can the product capture voice memos?
The hardware is there, but the microphone support has not been implemented in the firmware. It would have to wait that it gets ready. It would be possible to perform recording and extract the audio over Bluetooth.

Feel free to ask further questions as they come!
