### ISSUE TITLE
Lower idle power when Monocle is worn but not doing anything

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#152]
Queried from the chat.

https://discord.com/channels/963222352534048818/984966420603482182/1087157969596198993

**Comment by josuah** [comment]
ECS336CN is the last part that consumes a lot of power, it could be turned off.

**Comment by siliconwitch** [comment]
Similar how the camera sleeping is automatically handled within the driver, perhaps `display.clear()` could shut down the screen, and `display.show()` turns it back on again. Then the power stuff is transparent for the user and quite obvious that when the display is blank, it consumes the least amount of energy.

**Comment by siliconwitch** [comment]
This is now done using `fpga.run()`. If you do `fpga.run(False)`, it's the lowest power mode because it shuts down all the other rails except for the nRF52
