### ISSUE TITLE
[feature] Web-repl "new version" message

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#156]
Suggestion from the community

> A prompt that appears, not just a little thing on the side a modal with an explanation of the updates maybe latest release, feature bullet points

**Comment by josuah** [comment]
https://discord.com/channels/963222352534048818/984966420603482182/1088910047834288148

**Comment by siliconwitch** [comment]
If you click on the version number, it takes you to the release page with these details:

![Image](https://user-images.githubusercontent.com/7815190/227945898-c203ca1a-574e-4e93-8332-9d88c10ca36c.png)
