### ISSUE TITLE
Add streamlogic feature detection calls inside of __init__ for display, camera, etc

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#172]
The StreamLogic port comes with an feature and address detection API that permits to obtain the number of instance of some blocks as well as presence of others.

This can be useful in MicroPython to return informative error messages instead of just sending the bytes to the FPGA with no reaction, more difficult to debug.

**Comment by siliconwitch** [comment]
Since `display`, `camera`, and `microphone` are our custom libraries. I thought the simplest could be a simple API check that could happen during the import of the module. i.e. within `__init__`

**Comment by siliconwitch** [comment]
For any other features, we can let the user write (or inherit from the StreamLogic port) additional Python files and add them manually for their own custom bitstream

**Comment by josuah** [comment]
> Since `display`, `camera`, and `microphone` are our custom libraries. I thought the simplest could be an API check that happens during the import of the module. i.e. within `__init__`

I did not think of it, very nice!

> For any other features, we can let the user write (or inherit from the StreamLogic port) additional Python files and add them manually for their own custom bitstream

I assume that would be done with `fpga.read()` and `fpga.write()`.

For future reference, the feature detection code seems to lie down https://github.com/sathibault/streamlogic-monocle-micropython/blob/main/modules/fpgalib.c

**Comment by josuah** [comment]
I remember some rationale that a full custom FGPA binary is expected to be supported, so I understand better the need for keeping everything streamlogic-related outside the built-in files.
