### ISSUE TITLE
Enable `sys.modules` dict

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#175]
Currently, we have `#define MICROPY_PY_SYS_MODULES (0)`.

`sys.modules` permits to do things like this:

```python
del sys.modules["something"]
```

Some suggestion from @jimmo:
```python
class temp_scope:
    def __enter__(self):
        self.k = set(sys.modules.keys())

    def __exit__(self, ...):
        for k in set(sys.modules.keys()) - self.k:
            del sys.modules[k]

with temp_scope():
    from foo import *
    print(bar(42))
```

From Brilliant discord server:
https://discord.com/channels/963222352534048818/1060663901240442930/1096403411676708866
https://discord.com/channels/963222352534048818/1074359320969490452/1094251883717210132

From MicroPython discord server:
https://discord.com/channels/574275045187125269/574275045611012097/1011271986351198310

**Comment by siliconwitch** [comment]
Sounds good!
