### ISSUE TITLE
Improve splash screen

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#183]
The Monocle comes bare-bones. To be able to have a quick impression of its abilities, as well as allow to use it without any programming, a demo app could provide a set of core features.

Some examples from the chat:
https://discord.com/channels/963222352534048818/1100115561997934633/1100118956091654225

* Image transfer from the camera to the Bluetooth central (output)
* Show notifications from the Destkop (input)

The features from earlier firmware:

* Start continuous recording and offer to show a replay (eventually save it / transfer it?) of the camera feed
* Zoom the camera output.

**Comment by siliconwitch** [comment]
I can try come up with something for this
