### ISSUE TITLE
Display API: memory allocation failed

### ISSUE THREAD

**Issue by endanke** [brilliantlabsAR/monocle-micropython#187]
I'm trying to use the display API using the latest release (`v23.112.1046`) with the following two lines:
`import display; line = display.Line(500, 5, 500, 395, display.WHITE); display.show(line);`
`import display; line = display.Line(520, 5, 520, 395, display.WHITE); display.show(line);`

The first one works, but the second one produces this error:
```
Traceback (most recent call last):
  File "<stdin>", in <module>
  File "display.py", in show
MemoryError: memory allocation failed, allocating 16384 bytes
```

Is this expected or a bug?

**Comment by siliconwitch** [comment]
Is this the same as https://github.com/sathibault/vgrs/issues/8 @josuah ?

**Comment by josuah** [comment]
It is likely the same issue, and the latest dev branch from `vgrs` fixes it!
![mpv-shot0001](https://user-images.githubusercontent.com/55351021/236524742-ac70338b-deac-43c3-aa73-54f92f3f4c19.jpg)

**Comment by endanke** [comment]
@josuah @siliconwitch I can confirm that it works now, thanks a lot! :) Now I can render lines anywhere on the screen. :D 🎉
