### ISSUE TITLE
Text output randomly mixed-up

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#198]
Upon certain conditions, as well as randomly with the same code, the text output can become offset.

@jdc-cunningham did this reproducer:
https://gist.github.com/jdc-cunningham/ff37424802a8db87c317c7d7c5575f00 - breaking
https://gist.github.com/jdc-cunningham/117a4e38177043c03631d711db94691b - works

And developed the problem here: https://discord.com/channels/963222352534048818/1105933108617945268/1105954663204921416

Here the 46m should be at the top right corner of the display, and the "Re" should be on top of the white square:
![offset](https://cdn.discordapp.com/attachments/1105933108617945268/1105954663028756530/IMG_20230510_1528069132.jpg)

**Comment by siliconwitch** [comment]
Is this fixed now with the latest release?

**Comment by josuah** [comment]
Some of it is fixed, and the remaining bug will be discussed in #208.
Thank you!
