### ISSUE TITLE
Async code sometimes lead to firmware crash

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#203]
The code written by @nevyn highlighted a bug which makes the device misbehave, or sometimes crash:

https://discord.com/channels/963222352534048818/1107927061391233065
https://github.com/nevyn/allocle/blob/1f24d530cfed0d7d1977c644217944f5fd66a753/device%20files/main.py

**Comment by josuah** [comment]
This could be debugged with #228

**Comment by siliconwitch** [comment]
Testing for a while, this this seems stable now. Will reopen if it happens again
