### ISSUE TITLE
display.show() too slow

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#247]
It is overly slow for drawing animations, it looked faster in the past.

The animations tested were vertical built out of polygons.

**Comment by josuah** [comment]
Also adding the text to this text gives similar results:

```
2 FPS
19 FPS
18 FPS
19 FPS
18 FPS
19 FPS
18 FPS
19 FPS
18 FPS
```

Is it to be considered overly slow? It is not cinema-rate, but is fast enough to allow some movement.

https://en.wikipedia.org/wiki/Frame_rate#Animation shows a 12 FPS horse animation.

**Comment by siliconwitch** [comment]
Fine now. Closing
