### ISSUE TITLE
Text alignment jumping occasionally

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#249]
Occasionally, text displayed still becomes displayed with a random offset.

The problem was expected to be fixed by https://github.com/brilliantlabsAR/monocle-micropython/pull/239

Although it seems to still be present.

**Comment by josuah** [comment]
Through discussions  it was outlined that this seemed to be less frequent now.
It might be easier to aim a fix blindly, and observe how it evolves across the following months, as it becomes harder to reproduce that issue.

**Comment by siliconwitch** [comment]
Cancelled as this will be replaced with the sprites module soon
