### ISSUE TITLE
`led` module triggers crashes

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#256]
It is a very simple module, but apparently something might be wrong somewhere:
```
>>> import device
>>> device.VERSION
'v23.187.0945'
>>> import led
>>> while True: led.on(led.GREEN)
...
Device was disconnected.
```

This does not crash on https://github.com/josuah/monocle-nrf52dk which has a different implementation.

**Comment by siliconwitch** [comment]
Interesting! Seems this would clog the I2C with PMIC commands. Will test shortly
