### ISSUE TITLE
Implement media transfer over Bluetooth

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#4]
An extra Bluetooth service provides an extra stream used for binary data.

**Comment by josuah** [comment]
An extra Bluetooth service provides an extra stream used for binary data.

**Comment by josuah** [comment]
Waiting an app version that can pair with the Monocle.

**Comment by josuah** [comment]
Could not pair insofar with two phones.
Will work on that with Umar and Raj tomorrow.

**Comment by sena-mike** [comment]
Is there a spec available for the BLE services and characteristics offered over BLE?

**Comment by josuah** [comment]
The main bluetooth stream giving the python console is a standard [1] Nordic Uart Service, as the upstream micropython uses.

There is a secondary stream, using the same kind of TX and RX characteristics, that is used to transfer files.
@siliconwitch did a nice doc for it at https://docs.brilliantmonocle.com/micropython/micropython/#under-the-hood

**Comment by josuah** [comment]
The web REPL is also an interesting way to explore both protocols, as it gives a practical implementation to check against:
https://github.com/brilliantlabsar/web-bluetooth-repl
