### ISSUE TITLE
Device disconnections are not always detected

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-micropython#40]
When disconnected a device does is not always discoverable through bluetooth: no UUID128 grabbed by `./serial_console.py`.

No `assert()` or `app_err()`  triggered though.

**Comment by siliconwitch** [comment]
I think I know what this is. Will fix it when we're going over the BLE code. There are a couple of things I want to refactor there. Planned for later this week once power stuff and CC firmware is done and tested
