### ISSUE TITLE
`camera` module

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/monocle-micropython#85]
Functions required

- [x] overlay
- [ ] capture
- [x] zoom
- [ ] replay

**Comment by josuah** [comment]
Currently working on replay

**Comment by josuah** [comment]
Related:
https://github.com/brilliantlabsAR/monocle-fpga/issues/4

**Comment by siliconwitch** [comment]
Closed as this issue has been split into the individual parts
